### ISSUE TITLE
Not seeing files update in S3

### ISSUE THREAD

**Issue by nodeGarden** [otakuyu/hexo-deployer-aws-s3#1]
I am seeing it say Deploy done, but no changes to existing files on the S3 bucket.

![image](https://cloud.githubusercontent.com/assets/253262/11981027/b53ebade-a964-11e5-9a1c-d50114708622.png)

Is this working for you? None of the other forks of this have Issues enabled, so figured I'd see if it was actually working for you, then troubleshoot from there.

S3 Permissions:

![image](https://cloud.githubusercontent.com/assets/253262/11981094/15ede152-a965-11e5-9c75-f46c982cf9a2.png)

**Comment by otakuyu** [comment]
yup, it is working for me. What is the node version you are testing on?I assume you have setup aws key value pair right? @nodeGarden

**Comment by nodeGarden** [comment]
@otakuyu. Thanks for replying. I tried combinations of values, and lots of console.log, but it appeared that the code inside the `s3-sync` portion of this plugin wasn't even executing. I ended up writing my own plugin that uses the `s3` module (vs `s3-sync`), and have it all working now.
